name: CI

on: 
  workflow_dispatch:
  push:
    paths: 
      - puertstest/puerts/**
      - .github/workflows/ci.yml

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          cd pesapitest/pesaddon
          chmod 777 make_android.sh
          ANDROID_NDK=~/android-ndk-r21b ./make_android.sh
#  ios:
#    runs-on: macos-10.15
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Xcode 12.0 for x86
#        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
#      - name: Build
#        run: |
#          cd pesapitest/pesaddon
#          sh ./make_ios.sh
#      - name: Upload
#        uses: actions/upload-artifact@v2
#        with:
#          path: ./unity/Assets/Plugins/**/*
#          name: Unity_Plugins_V8
  osx:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd pesapitest/pesaddon
          sh ./make_osx.sh

  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd pesapitest\pesaddon
          .\make_win64.bat
          
  linux64:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install libc++-dev
        run: |
          sudo apt-get install clang
          sudo apt-get install libc++-dev
          sudo apt-get install libc++abi-dev
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cd pesapitest/pesaddon
          mkdir build_linux64
          cd build_linux64
          cmake ..
          make
